apiVersion: v1
data:
  secret.txt: bW9uZ29kYjovL2FkbWluVXNlcjpNb25nb1Bhc3N3b3JkMTIzIUByaGVsNzY2NHNwdDEtMjAxOS5ha2FuYS5yb2d1ZXdhdmUuY29tOjI3MDE3L0RvY1B1bHNlP2F1dGhTb3VyY2U9YWRtaW4K
kind: Secret
metadata:
  name: hawk-api-secret
  namespace: hawk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hawk
  labels:
    app: hawk-apiserver
  name: hawk-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hawk-apiserver
  strategy: {}
  template:
    metadata:
      labels:
        app: hawk-apiserver
    spec:
      containers:
      - image: immnan/hawk-apiserver:0.1.0
        name: hawk-apiserver
        ports:
        - containerPort: 3000
        env:  
        - name: CRED_FILE_PATH
          value: "/etc/hawk-api-server/secret.txt"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/hawk-apiserver/
          readOnly: true
      volumes:
      - name: config-volume
        secret: 
          secretName: hawk-api-secret


